POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ldyB1c2VyIiwiaWQiOiI2NWVjNGMzYWIzZTJhNTI3NWYxODg1NjAiLCJpYXQiOjE3MDk5ODQ4Mzd9.ZnZk_gzbZNHIqIWGfyLSuse0BQdOxEhNZHYxwCWujHs

{
  "title": "new blog",
  "author": "me",
  "url": "mockblogurl",
  "likes": 333
}