POST http://localhost:3001/api/blogs 
Content-Type: application/json

{
    "title": "My First Blog",
    "author": "Me",
    "url": "http://astonishingblog.om",
    "likes": 2222
}

######
GET http://localhost:3001/api/blogs 