POST http://localhost:3001/api/blogs 
Content-Type: application/json

{
    "title": "A staggering blog",
    "author": "Me",
    "url": "http://staggeringblog.om",
    "likes": 2222
}

######
GET http://localhost:3001/api/blogs 